"use client";
import { useState } from "react";
import { api } from "./api";
import type { Item } from "./workspace";
export const EXPERIENCE = [["NONE","Без опыта"],["UNDER_1","До 1 года"],["FROM_1_TO_3","1–3 года"],["FROM_3_TO_5","3–5 лет"],["OVER_5","5+ лет"]];
export const LEVEL = [["INTERN","Стажёр"],["JUNIOR","Junior"],["MIDDLE","Middle"],["SENIOR","Senior"]];
export const WORK = [["REMOTE","Удалённо"],["HYBRID","Гибрид"],["OFFICE","Офис"]];
export const EMPLOYMENT = [["FULL_TIME","Полная"],["PART_TIME","Частичная"],["PROJECT","Проектная"],["INTERNSHIP","Стажировка"]];
export function SelectField({ label, value, onChange, options, optional = false }: { label: string; value: string; onChange: (v: string) => void; options: string[][] | Item[]; optional?: boolean }) { return <label>{label}<select value={value || ""} onChange={e=>onChange(e.target.value)} required={!optional}>{optional && <option value="">Не выбрано</option>}{options.map(option => "id" in option ? <option key={option.id} value={option.id}>{option.name}</option> : <option key={option[0]} value={option[0]}>{option[1]}</option>)}</select></label>; }
export function TextField({ label, value, onChange, type = "text", required = false, maxLength, min }: { label: string; value: string | number; onChange: (v: string) => void; type?: string; required?: boolean; maxLength?: number; min?: number }) { return <label>{label}<input type={type} value={value ?? ""} required={required} maxLength={maxLength} min={min} onChange={e=>onChange(e.target.value)}/></label>; }
export function SkillPicker({ items, selected, onChange, label = "Навыки (минимум один)" }: { items: Item[]; selected: string[]; onChange: (ids: string[]) => void; label?: string }) { return <fieldset><legend>{label}</legend><div className="checkboxes">{items.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>onChange(e.target.checked ? [...selected,item.id] : selected.filter(id=>id!==item.id))}/>{item.name}</label>)}</div></fieldset>; }
export function ImageUpload({ kind, fileId, onChange, onLoadingChange }: { kind: "AVATAR" | "COMPANY_LOGO" | "COMPANY_PHOTO"; fileId?: string; onChange: (fileId: string) => void; onLoadingChange?: (loading: boolean) => void }) { const [error,setError]=useState(""),[loading,setLoading]=useState(false); return <label>{kind === "AVATAR" ? "Аватар" : kind === "COMPANY_LOGO" ? "Логотип" : "Фото компании"}{fileId && <img className="avatar" src={`/api/v1/media/${fileId}`} alt="Загруженное изображение"/>}<input type="file" disabled={loading} accept="image/png,image/jpeg,image/webp" onChange={async e=>{ const file=e.target.files?.[0]; if (!file) return; setLoading(true); onLoadingChange?.(true); setError(""); try { const form = new FormData(); form.append("kind",kind); form.append("file",file); const result=await api<{fileId:string}>("/media",{method:"POST",body:form}); onChange(result.fileId); } catch(err){setError((err as Error).message)} finally {setLoading(false); onLoadingChange?.(false); e.target.value=""} }}/>{loading && <span role="status">{kind === "AVATAR" ? "Обрабатываем фотографию…" : "Загрузка…"}</span>}{error && <span className="error" role="alert">{error}</span>}</label>; }
