"use client";
import { useEffect, useState } from "react";
import { api, send } from "./api";
import { ImageUpload, SelectField, TextField, WORK } from "./fields";
const blank={name:"",description:"",workFormat:"",foundedYear:"",sizeBand:"",industry:"",websiteUrl:"",logoFileId:"",contactEmail:"",telegram:"",phone:""};
export function CompanyPanel(){const[form,setForm]=useState<any>(blank),[exists,setExists]=useState(false),[photos,setPhotos]=useState<any[]>([]),[links,setLinks]=useState<any[]>([]),[newLink,setNewLink]=useState({platform:"TELEGRAM",value:""}),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  const refresh=()=>api<any>("/companies/me").then(x=>{setForm({...blank,...x});setExists(true);setPhotos(x.photos||[]);setLinks(x.socialLinks||[])}).catch(()=>{});
  useEffect(()=>{refresh()},[]);const set=(key:string,value:any)=>setForm((old:any)=>({...old,[key]:value}));
  async function save(event:React.FormEvent){event.preventDefault();setSaving(true);setMessage("");try{await send("/companies/me",exists?"PUT":"POST",{...form,foundedYear:Number(form.foundedYear)});setExists(true);setMessage("Компания сохранена");refresh()}catch(err){setMessage((err as Error).message)}finally{setSaving(false)}}
  return <div className="card"><h2>{exists?"Моя компания":"Создать компанию"}</h2><form onSubmit={save}><div className="form-grid"><TextField label="Название" value={form.name} onChange={v=>set("name",v)} required/><SelectField label="Формат работы" value={form.workFormat} onChange={v=>set("workFormat",v)} options={WORK}/><TextField label="Год основания" type="number" min={1800} value={form.foundedYear} onChange={v=>set("foundedYear",v)} required/><SelectField label="Размер компании" value={form.sizeBand} onChange={v=>set("sizeBand",v)} options={[["1-10","1–10"],["11-50","11–50"],["51-200","51–200"],["201-1000","201–1000"],["1000+","1000+"]]}/><TextField label="Сфера деятельности" value={form.industry} onChange={v=>set("industry",v)} required/><TextField label="Сайт" type="url" value={form.websiteUrl||""} onChange={v=>set("websiteUrl",v)}/></div><label>Краткое описание<textarea required maxLength={500} rows={4} value={form.description} onChange={e=>set("description",e.target.value)}/></label><ImageUpload kind="COMPANY_LOGO" fileId={form.logoFileId} onChange={v=>set("logoFileId",v)}/><h3>Контакты после Match</h3><div className="form-grid"><TextField label="Контактный email" type="email" value={form.contactEmail||""} onChange={v=>set("contactEmail",v)}/><TextField label="Telegram" value={form.telegram||""} onChange={v=>set("telegram",v)}/><TextField label="Телефон" type="tel" value={form.phone||""} onChange={v=>set("phone",v)}/></div><button disabled={saving||!form.logoFileId}>{saving?"Сохранение…":"Сохранить компанию"}</button>{message&&<p role="status">{message}</p>}</form>{exists&&<><h3>Дополнительные фотографии</h3><ImageUpload kind="COMPANY_PHOTO" onChange={async fileId=>{try{await send("/companies/me/photos","POST",{fileId});refresh()}catch(err){setMessage((err as Error).message)}}}/><div className="row">{photos.map(photo=><div key={photo.id}><img className="avatar" src={photo.url} alt="Фото компании"/><button className="secondary" onClick={async()=>{await send(`/companies/me/photos/${photo.id}`,"DELETE");refresh()}}>Удалить</button></div>)}</div><h3>Социальные сети</h3><div className="row"><select style={{width:180}} value={newLink.platform} onChange={e=>setNewLink({...newLink,platform:e.target.value})}><option value="TELEGRAM">Telegram</option><option value="INSTAGRAM">Instagram</option><option value="TIKTOK">TikTok</option><option value="OTHER">Другая</option></select><input style={{flex:1}} placeholder="Ссылка или username" value={newLink.value} onChange={e=>setNewLink({...newLink,value:e.target.value})}/><button onClick={async()=>{try{await send("/companies/me/social-links","POST",newLink);setNewLink({...newLink,value:""});refresh()}catch(err){setMessage((err as Error).message)}}}>Добавить</button></div>{links.map(link=><p key={link.id}>{link.platform}: {link.value} <button className="secondary" onClick={async()=>{await send(`/companies/me/social-links/${link.id}`,"DELETE");refresh()}}>Удалить</button></p>)}</>}</div>;
}
