"use client";
import { useEffect, useState } from "react";
import { Check } from "lucide-react";
import { api, send } from "./api";
import { SelectField, SkillPicker, TextField, WORK } from "./fields";
import { DIRECTIONS } from "./practice-options";
import { UiIcon } from "./ui-icon";
import type { Catalogs } from "./workspace";

const empty = { title: "", description: "", direction: "backend", slotsTotal: "1", practiceStartDate: "", practiceEndDate: "", workFormats: [] as string[], cityId: "", requiredSkillIds: [] as string[], optionalSkillIds: [] as string[], studyCourseMin: "", studyCourseMax: "", officialPracticeSupport: false, status: "ACTIVE" };
type Page = { items: any[]; total: number; page: number; pageSize: number };
const statusName: Record<string, string> = { DRAFT: "Черновик", ACTIVE: "Активен", COMPLETED: "Завершён", ARCHIVED: "Архив", SENT: "Отправлено", VIEWED: "Просмотрено", ACCEPTED: "Принято", DECLINED: "Отклонено", INTERVIEW: "Собеседование", HIRED: "Оформлено" };
const errorText = (err: unknown) => (err as Error).message;
const checkboxes = (options: string[][], selected: string[], onChange: (values: string[]) => void) => <div className="checkboxes">{options.map(([id,label])=><label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={event=>onChange(event.target.checked?[...selected,id]:selected.filter(value=>value!==id))}/>{label}</label>)}</div>;

export function EmployerPracticePanel({ catalogs }: { catalogs: Catalogs }) {
  const [list,setList]=useState<Page|null>(null),[selected,setSelected]=useState<any>(null),[matches,setMatches]=useState<Page|null>(null),[invites,setInvites]=useState<Page|null>(null),[form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[filters,setFilters]=useState<any>({direction:"",workFormat:"",cityId:"",studyCourse:"",dateFrom:"",dateTo:"",skillIds:[] as string[]}),[inviteCandidate,setInviteCandidate]=useState<any>(null),[profile,setProfile]=useState<any>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[contacts,setContacts]=useState<Record<string, any>>({});
  const refresh=async()=>{setLoading(true);try{const data=await api<Page>("/practice-recruitments?pageSize=100");setList(data);if(selected){const next=data.items.find(x=>x.id===selected.id);setSelected(next||null);}}catch(err){setMessage(errorText(err))}finally{setLoading(false)}};
  useEffect(()=>{api<Page>("/practice-recruitments?pageSize=100").then(setList).catch(err=>setMessage(errorText(err))).finally(()=>setLoading(false))},[]);
  const set=(key:string,value:any)=>setForm((old:any)=>({...old,[key]:value}));
  async function open(row:any){setSelected(row);setMessage("");try{const [m,i]=await Promise.all([api<Page>(`/practice-recruitments/${row.id}/matches?pageSize=100`),api<Page>(`/practice-recruitments/${row.id}/invitations?pageSize=100`)]);setMatches(m);setInvites(i)}catch(err){setMessage(errorText(err))}}
  async function applyFilters(){if(!selected)return;const params=new URLSearchParams({pageSize:"100"});for(const key of ["direction","workFormat","cityId","studyCourse","dateFrom","dateTo"])if(filters[key])params.set(key,filters[key]);for(const id of filters.skillIds)params.append("skillId",id);try{setMatches(await api<Page>(`/practice-recruitments/${selected.id}/matches?${params}`))}catch(err){setMessage(errorText(err))}}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const body={...form,slotsTotal:Number(form.slotsTotal),cityId:form.cityId||null,studyCourseMin:form.studyCourseMin?Number(form.studyCourseMin):null,studyCourseMax:form.studyCourseMax?Number(form.studyCourseMax):null};const result=await send<any>(editing?`/practice-recruitments/${editing}`:"/practice-recruitments",editing?"PUT":"POST",body);setForm(empty);setEditing(null);setMessage("Набор сохранён");await refresh();await open(result)}catch(err){setMessage(errorText(err))}finally{setBusy(false)}}
  async function changeStatus(status:"ACTIVE"|"ARCHIVED"){if(!selected)return;try{const row=await send<any>(`/practice-recruitments/${selected.id}/status`,"POST",{status});await refresh();await open(row)}catch(err){setMessage(errorText(err))}}
  async function invite(event:React.FormEvent){event.preventDefault();if(!selected||!inviteCandidate)return;setBusy(true);try{await send(`/practice-recruitments/${selected.id}/invitations`,"POST",{candidateUserId:inviteCandidate.candidate.userId,message:inviteCandidate.message});setInviteCandidate(null);setMessage("Приглашение отправлено");await open(await api<any>(`/practice-recruitments/${selected.id}`))}catch(err){setMessage(errorText(err))}finally{setBusy(false)}}
  async function move(id:string,action:"interview"|"hired"){try{await send(`/practice-invitations/${id}/${action}`,"POST");if(selected)await open(await api<any>(`/practice-recruitments/${selected.id}`));await refresh()}catch(err){setMessage(errorText(err))}}
  async function showContacts(id:string){try{const item=await api(`/practice-invitations/${id}/contacts`);setContacts(old=>({...old,[id]:item}))}catch(err){setMessage(errorText(err))}}
  return <><div className="card"><h2>Наборы на практику</h2><p className="muted">Внутренние запросы компании. Студенты видят только адресованные им приглашения.</p>{loading&&<p role="status">Загрузка…</p>}{list?.items.length===0&&<p>Пока нет наборов. Создайте первый ниже.</p>}{list?.items.map(row=><div className="row" key={row.id}><strong>{row.title}</strong><span>{statusName[row.status]}</span><span>{row.slotsFilled}/{row.slotsTotal} мест</span><button className="secondary" onClick={()=>open(row)}>Открыть</button></div>)}{message&&<p role="status">{message}</p>}</div>
    <div className="card"><h2>{editing?"Изменить набор":"Создать набор"}</h2><form onSubmit={save}><div className="form-grid"><TextField label="Название" value={form.title} onChange={v=>set("title",v)} required/><SelectField label="Направление" value={form.direction} onChange={v=>set("direction",v)} options={DIRECTIONS}/><TextField label="Количество мест" type="number" min={1} value={form.slotsTotal} onChange={v=>set("slotsTotal",v)} required/><TextField label="Начало" type="date" value={form.practiceStartDate} onChange={v=>set("practiceStartDate",v)} required/><TextField label="Окончание" type="date" value={form.practiceEndDate} onChange={v=>set("practiceEndDate",v)} required/><SelectField label="Город" value={form.cityId} onChange={v=>set("cityId",v)} options={catalogs.cities} optional/><TextField label="Курс от" type="number" min={1} value={form.studyCourseMin} onChange={v=>set("studyCourseMin",v)}/><TextField label="Курс до" type="number" min={1} value={form.studyCourseMax} onChange={v=>set("studyCourseMax",v)}/></div><label>Описание<textarea value={form.description} onChange={e=>set("description",e.target.value)} required rows={3}/></label><fieldset><legend>Формат практики</legend>{checkboxes(WORK,form.workFormats,(v)=>set("workFormats",v))}</fieldset><fieldset><legend>Обязательные навыки</legend><SkillPicker items={catalogs.skills} selected={form.requiredSkillIds} onChange={v=>set("requiredSkillIds",v)}/></fieldset><fieldset><legend>Желательные навыки</legend><SkillPicker items={catalogs.skills} selected={form.optionalSkillIds} onChange={v=>set("optionalSkillIds",v)} label="Навыки (необязательно)"/></fieldset><label className="row"><input type="checkbox" style={{width:"auto"}} checked={form.officialPracticeSupport} onChange={e=>set("officialPracticeSupport",e.target.checked)}/>Компания готова официально оформить практику</label><SelectField label="Статус" value={form.status} onChange={v=>set("status",v)} options={[["ACTIVE","Активен"],["DRAFT","Черновик"]]}/><div className="row"><button disabled={busy}>Сохранить и найти студентов</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm(empty)}}>Отмена</button>}</div></form></div>
    {selected&&<div className="card"><h2>{selected.title}</h2><p>{statusName[selected.status]} · {selected.slotsFilled} из {selected.slotsTotal} мест заполнено · осталось {selected.remaining}</p><p>Найдено: {matches?.total??0} · приглашено: {selected.stats.invited} · приняли: {selected.stats.accepted}</p><div className="row">{selected.status==="DRAFT"&&<button onClick={()=>changeStatus("ACTIVE")}>Активировать</button>}{["ACTIVE","DRAFT","COMPLETED"].includes(selected.status)&&<button className="secondary" onClick={()=>changeStatus("ARCHIVED")}>В архив</button>}{["ACTIVE","DRAFT"].includes(selected.status)&&selected.stats.invited===0&&<button className="secondary" onClick={()=>{setEditing(selected.id);setForm({...selected,slotsTotal:String(selected.slotsTotal),cityId:selected.cityId||"",studyCourseMin:String(selected.studyCourseMin||""),studyCourseMax:String(selected.studyCourseMax||"")})}}>Изменить</button>}</div>
      <h3>Подходящие студенты</h3><details><summary>Фильтры</summary><div className="form-grid"><SelectField label="Направление" value={filters.direction} onChange={v=>setFilters({...filters,direction:v})} options={DIRECTIONS} optional/><SelectField label="Формат" value={filters.workFormat} onChange={v=>setFilters({...filters,workFormat:v})} options={WORK} optional/><SelectField label="Город" value={filters.cityId} onChange={v=>setFilters({...filters,cityId:v})} options={catalogs.cities} optional/><TextField label="Курс" type="number" min={1} value={filters.studyCourse} onChange={v=>setFilters({...filters,studyCourse:v})}/><TextField label="Период от" type="date" value={filters.dateFrom} onChange={v=>setFilters({...filters,dateFrom:v})}/><TextField label="Период до" type="date" value={filters.dateTo} onChange={v=>setFilters({...filters,dateTo:v})}/></div><SkillPicker items={catalogs.skills} selected={filters.skillIds} onChange={v=>setFilters({...filters,skillIds:v})}/><p className="muted">Фильтр подтверждённых достижений появится после подключения ФСП.</p><button onClick={applyFilters}>Применить</button></details>{matches?.items.length===0&&<p>Подходящих студентов пока нет.</p>}{matches?.items.map(item=><article className="card" key={item.candidate.userId}><span className="practice-badge">ПРАКТИКА</span><h3>{item.candidate.firstName} {item.candidate.lastName} · {item.score}%</h3><p>{item.candidate.educationalInstitution} · {item.candidate.studyCourse} курс · {item.candidate.practiceStartDate} — {item.candidate.practiceEndDate}</p><p>Навыки: {item.candidate.skills.map((skill:any)=>skill.name).join(", ")}</p><details><summary>Почему {item.score}%?</summary>{item.reasons.map((reason:any,index:number)=><p key={index}>{reason.type==="positive"?<UiIcon icon={Check} size={14} />:<span aria-hidden="true">~</span>} {reason.text}</p>)}</details><div className="row"><button className="secondary" onClick={()=>setProfile(item.candidate)}>Посмотреть профиль</button>{selected.status==="ACTIVE"&&selected.remaining>0&&<button onClick={()=>setInviteCandidate({...item,message:"Здравствуйте! Приглашаем вас пройти производственную практику в нашей компании."})}>Пригласить на практику</button>}</div></article>)}
      {profile&&<div className="card"><h3>{profile.firstName} {profile.lastName}</h3><p>{profile.profession} · {profile.educationalInstitution} · {profile.studyCourse} курс</p><p>{profile.about}</p><p>Направления: {profile.desiredDirections?.join(", ")}</p><p>Навыки: {profile.skills?.map((skill:any)=>skill.name).join(", ")}</p><p>{profile.githubUrl&&<a href={profile.githubUrl}>GitHub</a>} {profile.portfolioUrl&&<a href={profile.portfolioUrl}>Портфолио</a>}</p><p className="muted">Контакты доступны после принятия приглашения.</p><button className="secondary" onClick={()=>setProfile(null)}>Закрыть</button></div>}<h3>Приглашённые</h3>{invites?.items.length===0&&<p>Приглашений пока нет.</p>}{invites?.items.map(row=><div className="card" key={row.id}><strong>{row.candidateName}</strong><p>{statusName[row.status]} · {new Date(row.createdAt).toLocaleDateString("ru-RU")}</p><div className="row">{row.status==="ACCEPTED"&&<button onClick={()=>move(row.id,"interview")}>Собеседование</button>}{row.status==="INTERVIEW"&&selected.status==="ACTIVE"&&selected.remaining>0&&<button onClick={()=>move(row.id,"hired")}>Оформлено</button>}{["ACCEPTED","INTERVIEW","HIRED"].includes(row.status)&&<button className="secondary" onClick={()=>showContacts(row.id)}>Контакты</button>}</div>{contacts[row.id]&&<p>{contacts[row.id].email} {contacts[row.id].telegram}</p>}</div>)}</div>}
    {inviteCandidate&&<div className="card" role="dialog" aria-modal="true" aria-label="Пригласить на практику"><h2>Пригласить {inviteCandidate.candidate.firstName}</h2><p>{selected.title} · {selected.practiceStartDate} — {selected.practiceEndDate}</p>{selected.officialPracticeSupport&&<p>Компания оформляет практику официально</p>}<form onSubmit={invite}><label>Сообщение<textarea value={inviteCandidate.message} onChange={e=>setInviteCandidate({...inviteCandidate,message:e.target.value})} required/></label><div className="row"><button disabled={busy}>Отправить приглашение</button><button type="button" className="secondary" onClick={()=>setInviteCandidate(null)}>Отмена</button></div></form></div>}</>;
}

export function SpecialistPracticePanel({onChanged}:{onChanged?:()=>void}){const[data,setData]=useState<Page|null>(null),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[contacts,setContacts]=useState<Record<string, any>>({});const refresh=async()=>{setLoading(true);try{setData(await api<Page>("/practice-invitations?pageSize=100"));onChanged?.()}catch(err){setMessage(errorText(err))}finally{setLoading(false)}};useEffect(()=>{api<Page>("/practice-invitations?pageSize=100").then(setData).catch(err=>setMessage(errorText(err))).finally(()=>setLoading(false))},[]);async function view(row:any){if(row.status==="SENT"){try{await send(`/practice-invitations/${row.id}/view`,"POST");await refresh()}catch(err){setMessage(errorText(err))}}}async function respond(id:string,action:"accept"|"decline"){try{await send(`/practice-invitations/${id}/${action}`,"POST");setMessage(action==="accept"?"Приглашение принято":"Приглашение отклонено");await refresh()}catch(err){setMessage(errorText(err))}}async function showContacts(id:string){try{const item=await api(`/practice-invitations/${id}/contacts`);setContacts(old=>({...old,[id]:item}))}catch(err){setMessage(errorText(err))}}return <div className="card"><h2>Приглашения на практику</h2>{loading&&<p role="status">Загрузка…</p>}{message&&<p role="status">{message}</p>}{data?.items.length===0&&<p>Приглашений пока нет. Заполните профиль практики, чтобы работодатели могли вас найти.</p>}{data?.items.map(row=><article key={row.id} className="card"><span className="practice-badge">ПРАКТИКА</span><h3>{row.companyName} · {row.recruitment.title}</h3><p>{row.recruitment.practiceStartDate} — {row.recruitment.practiceEndDate} · {row.recruitment.workFormats.map((format:string)=>WORK.find(([id])=>id===format)?.[1]||format).join(", ")}{row.recruitment.cityName?` · ${row.recruitment.cityName}`:""}</p>{row.recruitment.officialPracticeSupport&&<p>Компания оформляет практику официально</p>}<p>{row.message}</p><p>Статус: {statusName[row.status]}</p><div className="row">{row.status==="SENT"&&<button className="secondary" onClick={()=>view(row)}>Отметить просмотренным</button>}{["SENT","VIEWED"].includes(row.status)&&<><button onClick={()=>respond(row.id,"accept")}>Принять</button><button className="secondary" onClick={()=>respond(row.id,"decline")}>Отклонить</button></>}{["ACCEPTED","INTERVIEW","HIRED"].includes(row.status)&&<button className="secondary" onClick={()=>showContacts(row.id)}>Контакты компании</button>}</div>{contacts[row.id]&&<p>{contacts[row.id].contactEmail||contacts[row.id].email} {contacts[row.id].telegram} {contacts[row.id].phone}</p>}</article>)}</div>}
