"use client";
import { useEffect, useState } from "react";
import { api, send } from "./api";
import { EXPERIENCE, EMPLOYMENT, ImageUpload, LEVEL, SelectField, SkillPicker, TextField, WORK } from "./fields";
import type { Catalogs } from "./workspace";
const blank = { firstName:"",lastName:"",birthDate:"",cityId:"",avatarFileId:"",professionId:"",experience:"",level:"",cooperationType:"",skillIds:[] as string[],about:"",portfolioUrl:"",githubUrl:"",behanceGitlabUrl:"",telegram:"",salaryMinRub:"",salaryMaxRub:"",workFormat:"",employmentType:"",searchStatus:"OPEN_TO_OFFERS" };
export function SpecialistPanel({ catalogs }: { catalogs: Catalogs }) { const [form,setForm]=useState<any>(blank),[exists,setExists]=useState(false),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[processingPhoto,setProcessingPhoto]=useState(false);
  useEffect(()=>{ api<any>("/specialists/me").then(x=>{setForm({...blank,...x,skillIds:x.skills.map((s:any)=>s.id),birthDate:x.birthDate||""});setExists(true)}).catch(()=>{}); },[]);
  const set=(key:string,value:any)=>setForm((old:any)=>({...old,[key]:value}));
  async function save(event:React.FormEvent){event.preventDefault();if(processingPhoto)return;setSaving(true);setMessage("");try{const body={...form,birthDate:form.birthDate||null,cityId:form.cityId||null,experience:form.experience||null,level:form.level||null,cooperationType:form.cooperationType||null,workFormat:form.workFormat||null,employmentType:form.employmentType||null,salaryMinRub:Number(form.salaryMinRub),salaryMaxRub:Number(form.salaryMaxRub)};await send("/specialists/me",exists?"PUT":"POST",body);setExists(true);setMessage("Профиль сохранён и опубликован")}catch(err){setMessage((err as Error).message)}finally{setSaving(false)}}
  return <div className="card"><h2>{exists?"Мой профиль":"Создать профиль"}</h2><form onSubmit={save}><div className="form-grid"><TextField label="Имя" value={form.firstName} onChange={v=>set("firstName",v)} required/><TextField label="Фамилия" value={form.lastName} onChange={v=>set("lastName",v)} required/><TextField label="Дата рождения" type="date" value={form.birthDate} onChange={v=>set("birthDate",v)}/><SelectField label="Город" value={form.cityId} onChange={v=>set("cityId",v)} options={catalogs.cities} optional/><SelectField label="Специализация" value={form.professionId} onChange={v=>set("professionId",v)} options={catalogs.professions}/><SelectField label="Опыт" value={form.experience} onChange={v=>set("experience",v)} options={EXPERIENCE} optional/><SelectField label="Уровень" value={form.level} onChange={v=>set("level",v)} options={LEVEL} optional/><SelectField label="Тип сотрудничества" value={form.cooperationType} onChange={v=>set("cooperationType",v)} options={[["STAFF","Штат"],["PROJECT","Проект"],["FREELANCE","Фриланс"],["INTERNSHIP","Стажировка"]]} optional/><TextField label="Зарплата от, ₽/мес" type="number" min={1} value={form.salaryMinRub} onChange={v=>set("salaryMinRub",v)} required/><TextField label="Зарплата до, ₽/мес" type="number" min={1} value={form.salaryMaxRub} onChange={v=>set("salaryMaxRub",v)} required/><SelectField label="Формат работы" value={form.workFormat} onChange={v=>set("workFormat",v)} options={WORK} optional/><SelectField label="Занятость" value={form.employmentType} onChange={v=>set("employmentType",v)} options={EMPLOYMENT} optional/><SelectField label="Статус поиска" value={form.searchStatus} onChange={v=>set("searchStatus",v)} options={[["ACTIVE","Активно ищу"],["OPEN_TO_OFFERS","Открыт к предложениям"],["NOT_LOOKING","Не ищу"]]}/></div><ImageUpload kind="AVATAR" fileId={form.avatarFileId} onChange={v=>set("avatarFileId",v)} onLoadingChange={setProcessingPhoto}/><SkillPicker items={catalogs.skills} selected={form.skillIds} onChange={v=>set("skillIds",v)}/><label>О себе (до 500 символов)<textarea maxLength={500} rows={4} value={form.about||""} onChange={e=>set("about",e.target.value)}/></label><div className="form-grid"><TextField label="Портфолио" type="url" value={form.portfolioUrl||""} onChange={v=>set("portfolioUrl",v)}/><TextField label="GitHub" type="url" value={form.githubUrl||""} onChange={v=>set("githubUrl",v)}/><TextField label="Behance / GitLab" type="url" value={form.behanceGitlabUrl||""} onChange={v=>set("behanceGitlabUrl",v)}/><TextField label="Telegram" value={form.telegram||""} onChange={v=>set("telegram",v)}/></div><p className="muted">PDF резюме: загрузка появится позже.</p><button disabled={saving||processingPhoto||!form.avatarFileId}>{saving?"Сохранение…":"Сохранить профиль"}</button>{message&&<p role="status">{message}</p>}</form></div>;
}
